POST http://localhost:8081/new?uri=/about/
Accept: */*
content-type: application/json
Cache-Control: no-cache

{"text": "Stop saying that! *isso*!", "author": "Max Rant", "email": "rant@example.com", "parent": 3}

###

